---
  - name: Install Basic Packages
    hosts: 
    tasks:
      - name: Snap
        dnf:
          name: snapd
          state: latest       
      - name: Terminator
        dnf:
          name: terminator
          state: latest
      - name: Yakuake
        dnf:
          name: yakuake
          state: latest
      - name: Fish Shell
        dnf:
          name: fish
          state: latest
      - name: WGET
        dnf:
          name: wget
          state: latest
      - name: Cockpit
        dnf:
          name: cockpit
          state: latest
      - name: Audacity
        dnf:
          name: audacity
          state: latest

  - name: Download and Install RPMs
    hosts:  
    tasks:
      - name: Download Vivaldi
        get_url:
          url: https://downloads.vivaldi.com/stable/vivaldi-stable-3.2.1967.47-1.x86_64.rpm
          dest: /home/$USER/Downloads/
      - name: Install Vivaldi
        dnf:
          name: /home/$USER/Downloads/vivaldi-stable-3.2.1967.47-1.x86_64.rpm
          state: present
      - name: Download OnlyOffice
        get_url: 
          url: https://download.onlyoffice.com/install/desktop/editors/onlyoffice-desktopeditors.x86_64.rpm
          dest: /home/$USER/Downloads/
      - name: Install OnlyOffice
        dnf:
          name: /home/$USER/Downloads/onlyoffice-desktopeditors.x86_64.rpm
          state: present
      - name: Download RealVNCViewer
        get_url: 
          url: https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.20.529- -x64.rpm
          dest: /home/$USER/Downloads
      - name: Install RealVNCViewer
        dnf:
          name: /home/$USER/Downloads/VNC-Viewer-6.20.529- -x64.rpm
          state: present
      - name: Download Zoom
        get_url: 
          url: https://zoom.us/client/latest/zoom_x86_64.rpm
          dest: /home/$USER/Downloads
      - name: Install Zoom
        dnf: 
          name: /home/$USER/Downloads/zoom_x86_64.rpm
          state: present
      - name: Dowload MS Fonts
        # Not using get_url due to unusual URL
        action: shell wget -P /home/$USER/Downloads https://sourceforge.net/projects/mscorefonts2/files/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm/download -O msttcore-fonts-installer-2.6-1.noarch.rpm 
      - name: Install MS Fonts
        dnf:
          name: /home/$USER/Downloads/msttcore-fonts-installer-2.6-1.noarch.rpm
          state: present
      - name: Download Joplin
        get_url: 
          url: https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
          dest: /home/$USER/Downloads
      -name: Install Joplin
        shell: sudo sh /home/$USER/Downloads/Joplin_install_and_update.sh

  - name: Install Basic Terminal Tools
    hosts:  
    tasks:
      - name: Htop
        dnf:
          name: htop
          state: latest
      - name: Net-Tools
        dnf:
          name: net-tools
          state: latest
      - name: Nmap
        dnf:
          name: nmap
          state: latest
      - name: IOtop
        dnf:
          name: iotop
          state: latest
      - name: IFtop
        dnf:
          name: iftop
          state: latest
  
  - name: Install Snaps
    hosts:  
    tasks:
      - name: Telegram
        snap:
          name: telegram-desktop
      - name: Spotify
        snap:
          name: spotify
      - name: Super Productivity
        snap:
          name: superproductivity
      - name: Minecraft
        snap:
          name: mc-installer

  - name: Configuring RPM Fusion and Installing Packages
    hosts:
    tasks:
      - name: Add Repository
        dnf:
          name:
            - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm'
            - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
          state: present
      - name: Install OBS
        dnf:
          name: obs-studio
          state: latest
      - name: Install Kdenlive
        dnf:
          name: kdenlive
          state: latest

  - name: Basic System Configuration
    hosts:
    tasks:
      - name: Setting Default Shell to fish
        user:
          user: ryan
          shell: /bin/fish
      - name: Configuring Fish
        shell: echo "#Remove Fish Welcome Message" >> ~/.config/fish/config.fish && echo "function fish_greeting" >> ~/.config/fish/config.fish && echo "end" >> ~/.config/fish/config.fish
      - name: Generate SSH Keys
        user:
          generate_ssh_key: yes
          ssh_key_bits: 2048
          ssh_key_file: .ssh/id_rsa